version: '3.1'
services:
  springboot:
    image: suchitraapalav/maven-web-application:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
